#ifndef __LANGUAGES_H__
#define __LANGUAGES_H__

enum {

	LANG_UNKNOWN = 0,

	// Menu
	LANG_MENU_FILE,
	LANG_MENU_EXIT,
	LANG_MENU_TASK,
	LANG_MENU_START,
	LANG_MENU_STOP,
	LANG_MENU_STOP_DETACH,
	LANG_MENU_PAUSE_RESUME,
	LANG_MENU_HIDE_GAME,
	LANG_MENU_NEW,
	LANG_MENU_EDIT,
	LANG_MENU_CLONE,
	LANG_MENU_DELETE,
	LANG_MENU_OPTIONS,
	LANG_MENU_LANGUAGES,
	LANG_MENU_CHANGE_PASSWORD,
	LANG_MENU_SETTINGS,
	LANG_MENU_HELP,
	LANG_MENU_ABOUT,
	LANG_MENU_TASK_LIST,
	LANG_MENU_HIDE_ALL,
	LANG_MENU_SHOW_ALL,
	LANG_MENU_STOP_ALL,
	LANG_MENU_OK,
	LANG_MENU_CANCEL,

	// About window
	LANG_ABOUT_TITLE,
	LANG_ABOUT_COPYRIGHT,

	// Main window
	LANG_MAIN_LOG,
	LANG_MAIN_SUGGEST_CLEAN,
	LANG_MAIN_LIST_COLUMN_NAME,
	LANG_MAIN_LIST_COLUMN_AGE,
	LANG_MAIN_LIST_COLUMN_PROFILE,
	LANG_MAIN_FRAME_BATCH_OPER,
	LANG_MAIN_FRAME_TASK_DATA,
	LANG_MAIN_OPEN_LOG,
	LANG_MAIN_CLEAN_LOG,

	// Log
	LANG_LOG_APP_STARTED,
	LANG_LOG_APP_EXIT,
	LANG_LOG_PASSWORD_CREATED,
	LANG_LOG_LOGIN_SUCCESSFUL,
	LANG_LOG_INVALID_PASSWORD,
	LANG_LOG_DATA_DELETED,
	LANG_LOG_DATA_NOT_FOUND,
	LANG_LOG_DATA_LOADED,
	LANG_LOG_DATA_SAVED,
	LANG_LOG_KILLED_BLIZZARD_ERROR,
	LANG_LOG_TASK_CREATED,
	LANG_LOG_TASK_MODIFIED,
	LANG_LOG_TASK_DELETED,
	LANG_LOG_PASSWORD_CHANGED,
	LANG_LOG_MONITOR_TRIPWIRE,
	LANG_LOG_MONITOR_DIABLO_CLOSED,
	LANG_LOG_MONITOR_DEMONBUDDY_CLOSED,
	LANG_LOG_MONITOR_OUT_OF_GAME,
	LANG_LOG_MONITOR_DIABLO_DISCONNECTED,
	LANG_LOG_MONITOR_DIABLO_UNRESPONSIVE,
	LANG_LOG_MONITOR_DEMONBUDDY_UNRESPONSIVE,
	LANG_LOG_MONITOR_DIABLO_MINIMIZED,
	LANG_LOG_SET_HIDE_WINDOW_TRUE,
	LANG_LOG_SET_HIDE_WINDOW_FALSE,
	LANG_LOG_DIABLO_LOGIN_SCREEN,
	LANG_LOG_DIABLO_LOGIN_SUCCESS,
	LANG_LOG_DIABLO_LOGIN_FAILED,
	LANG_LOG_DIABLO_GAME_JOINED,
	LANG_LOG_DIABLO_GAME_LEFT,
	LANG_LOG_DIABLO_GAME_DISCONNECTED,
	LANG_LOG_LAUNCH_ERROR_RETRY,
	LANG_LOG_LAUNCH_PREPARE,
	LANG_LOG_LAUNCH_CLEANUP,
	LANG_LOG_LAUNCH_PREPARE_DIABLO,
	LANG_LOG_LAUNCH_START_DIABLO,
	LANG_LOG_LAUNCH_START_DIABLO_FAILED,
	LANG_LOG_LAUNCH_DIABLO_REUSED,
	LANG_LOG_LAUNCH_DIABLO_SUCCESS,
	LANG_LOG_LAUNCH_WAIT_DIABLO,
	LANG_LOG_LAUNCH_WAIT_BNET_LOGIN,
	LANG_LOG_LAUNCH_BNET_LOGIN_TIMEOUT,
	LANG_LOG_LAUNCH_WAIT_JOIN_GAME,
	LANG_LOG_LAUNCH_JOIN_GAME_FAILED,
	LANG_LOG_LAUNCH_PREPARE_DEMONBUDDY,
	LANG_LOG_LAUNCH_START_DEMONBUDDY,
	LANG_LOG_LAUNCH_START_DEMONBUDDY_FAILED,
	LANG_LOG_LAUNCH_DEMONBUDDY_REUSED,
	LANG_LOG_LAUNCH_WAIT_DEMONBUDDY,
	LANG_LOG_LAUNCH_DEMONBUDDY_SUCCESS,
	LANG_LOG_LAUNCH_CLOSE_DEMONBUDDY_ERROR,
	LANG_LOG_LAUNCH_CLOSE_DEMONBUDDY,
	LANG_LOG_LAUNCH_CHECK_DEMONBUDDY_CLOSE,
	LANG_LOG_LAUNCH_DEMONBUDDY_CLOSED,
	LANG_LOG_LAUNCH_WAIT_GAME_STABLIZE,
	LANG_LOG_LAUNCH_SUCCESSFUL,
	LANG_LOG_LAUNCH_HIDE_PROCESSES,
	LANG_LOG_STATE_LAUNCH,
	LANG_LOG_STATE_MONITOR,
	LANG_LOG_STATE_START,
	LANG_LOG_STATE_STOP,
	LANG_LOG_STATE_PAUSE,
	LANG_LOG_STATE_RESUME,

	// Message box
	LANG_MSG_INVALID_INPUT_TITLE,
	LANG_MSG_CREATE_PASSWORD_TITLE,
	LANG_MSG_CREATE_PASSWORD_TEXT,
	LANG_MSG_DELETE_TASK_TITLE,
	LANG_MSG_DELETE_TASK_TEXT,
	LANG_MSG_CLEAN_LOG_TITLE,
	LANG_MSG_CLEAN_LOG_TEXT,
	LANG_MSG_STOP_ALL_TITLE,
	LANG_MSG_STOP_ALL_TEXT,
	LANG_MSG_EXIT_APP_TITLE,
	LANG_MSG_TASK_RUNNING_TITLE,
	LANG_MSG_TASK_RUNNING_TEXT,
	LANG_MSG_TASK_CONFLICT_TITLE,
	LANG_MSG_TASK_CONFLICT_TEXT,
	LANG_MSG_INPUT_CANNOT_BE_EMPTY,
	LANG_MSG_INPUT_INVALID_PATH,
	LANG_MSG_DELETE_DATA_TITLE,
	LANG_MSG_DELERE_DATA_TEXT,
	LANG_MSG_PASSWORD_REPEAT_MISMATCH,
	LANG_MSG_ORIGINAL_PASSWORD_INCORRECT,

	// Password window
	LANG_PASSWORD_TITLE,
	LANG_PASSWORD_PASSWORD,
	LANG_PASSWORD_OLD_PASSWORD,
	LANG_PASSWORD_INVALID_TITLE,
	LANG_PASSWORD_INVALID_TEXT,
	LANG_PASSWORD_RETRY,
	LANG_PASSWORD_CLEAN_EXIT,
	LANG_PASSWORD_CREATE_TITLE,
	LANG_PASSWORD_CREATE_NEW_PASSWORD,
	LANG_PASSWORD_CREATE_REPEAT_PASSWORD,

	// Task window
	LANG_TASK_TITLE,
	LANG_TASK_FRAME_TASK,
	LANG_TASK_TASK_NAME,
	LANG_TASK_DIABLO_PATH,
	LANG_TASK_ACCOUNT,
	LANG_TASK_PASSWORD,
	LANG_TASK_I_USE_BNET_AUTHENTICATOR,
	LANG_TASK_SERIAL,
	LANG_TASK_RESTORE_CODE,
	LANG_TASK_DEMONBUDDY_PATH,
	LANG_TASK_AUTHORIZE_CODE,
	LANG_TASK_PROFILE_PATH,

	// Config window
	LANG_CONFIG_TITLE,
	LANG_CONFIG_DBLCLK_TASK_LIST,
	LANG_CONFIG_NO_OPERATION,
	LANG_CONFIG_OPEN_TASK_EDITING_WINDOW,
	LANG_CONFIG_CYCLE_START_STOP,
	LANG_CONFIG_CYCLE_START_STOP_NO_KILL,
	LANG_CONFIG_CYCLE_START_PAUSE_RESUME,
	LANG_CONFIG_TASK_CONTROL,
	LANG_CONFIG_PREVENT_DIABLO_MINIMIZED,
	LANG_CONFIG_MONITOR_TRIPWIRE_EVENT,
	LANG_CONFIG_DOUBLE_LAUNCH_DEMONBUDDY,
	LANG_CONFIG_ATTACH_EXISTING_PROCESSES,
	LANG_CONFIG_TIMEOUT,
	LANG_CONFIG_TIMEOUT_LAUNCH_DIABLO,
	LANG_CONFIG_TIMEOUT_BNET_LOGIN,
	LANG_CONFIG_TIMEOUT_CREATE_GAME,
	LANG_CONFIG_TIMEOUT_OUT_OF_GAME,
	LANG_CONFIG_TIMEOUT_GAME_DISCONNECTED,
	LANG_CONFIG_TIMEOUT_DIABLO_UNRESPONSIVE,
	LANG_CONFIG_TIMEOUT_DEMONBUDDY_UNRESPONSIVE,
	LANG_CONFIG_FORCE_RESTART_IF_TIMEOUT,
	LANG_CONFIG_TOOLTIP_PREVENT_MIN,
	LANG_CONFIG_TOOLTIP_DB_2X_LOGIN,
	LANG_CONFIG_TOOLTIP_TAKEOVER_PROCESS,
	LANG_CONFIG_RESTORE_DEFAULTS,
	LANG_CONFIG_SECONDS,
};

#include <afxtempl.h>

typedef CMap<int, int, CString, LPCTSTR> CLangMap;
typedef void (CALLBACK *FN_LOCALE_PROVIDER)(CLangMap& aMap);

class CLanguage
{
public:
	
	CLanguage();
	~CLanguage();

	CString GetText(int nID) const;
	BOOL SetLocale(LPCTSTR lpszLocale);
	CString GetLocale() const;
	int GetLocaleCount() const;
	BOOL GetLocale(int nIndex, CString& rLocale, CString& rName) const;
	static CString GetDefaultLocale();

private:

	static void CALLBACK Provider_English(CLangMap& aMap); // english
	static void CALLBACK Provider_Chinese_Simplified(CLangMap& aMap); // chinese-simplified
	static void CALLBACK Provider_Chinese_Traditional(CLangMap& aMap); // chinese-traditional

private:
	
	struct LANGUAGE_ENTRY
	{
		TCHAR szName[64];
		TCHAR szLocale[32];
		LPVOID lpFunc;
	};

	void RegisterLocale(LPCTSTR lpszLocale, LPCTSTR lpszName, FN_LOCALE_PROVIDER fnProvider);
	int FindDataByLocale(LPCTSTR lpszLocale) const;

	CLangMap m_aMap;
	CArray<LANGUAGE_ENTRY, const LANGUAGE_ENTRY&> m_aEntries;
	CString m_sLocale;
};

#endif // __LANGUAGES_H__