//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ARelogger.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_TMR_TICK                     101
#define IDD_ARELOGGER_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_BOTDLG                      129
#define IDD_NEWPWDDLG                   131
#define IDD_PWDDLG                      132
#define IDD_LOGINFAILDLG                133
#define IDR_MENU1                       134
#define IDR_MENU_TRAY                   134
#define IDB_HDR_IMG                     135
#define IDB_BOT_IMG                     136
#define IDR_TOOLBAR1                    137
#define IDR_MENU_MAIN                   139
#define IDD_CONFIGDLG                   140
#define IDC_BOTLIST                     1000
#define IDC_NEW                         1001
#define IDC_DIABLOPATH                  1002
#define IDC_USERACCOUNT                 1003
#define IDC_USERPASSWORD                1004
#define IDC_USEBNETAUTH                 1005
#define IDC_BNETSERIAL                  1006
#define IDC_EDIT                        1006
#define IDC_BNETRESTORECODE             1007
#define IDC_PWD                         1007
#define IDC_DELETE                      1007
#define IDC_PWD2                        1008
#define IDC_CLONE                       1008
#define IDC_DEMONBUDDYPATH              1009
#define IDC_CLEAR                       1009
#define IDC_DEMONBUDDYKEY               1010
#define IDC_VERINFO                     1010
#define IDC_PROFILEPATH                 1011
#define IDC_NAME                        1012
#define IDC_RUN                         1012
#define IDC_ABOUTVER                    1014
#define IDC_LOG                         1015
#define IDC_STOP                        1016
#define IDC_PAUSE                       1017
#define IDC_SETTINGS                    1018
#define IDC_EXIT                        1019
#define IDC_OPENLOG                     1020
#define IDC_CLEARLOG                    1021
#define IDC_LABEL                       1022
#define IDC_DB_2X_LOGIN                 1025
#define IDC_PREVENT_MIN                 1026
#define IDC_TIME_LAUNCHGAME             1027
#define IDC_TRIPWIRE                    1028
#define IDC_TIME_JOIN                   1029
#define IDC_TIME_LEAVE                  1030
#define IDC_TIME_DISCONNECT             1031
#define IDC_TIME_GAME_HUNG              1032
#define IDC_TIME_DB_HUNG                1033
#define IDC_DEFAULT                     1034
#define IDC_LOGSIZE                     1035
#define IDC_TIME_LOGIN                  1035
#define IDC_HIDEALL                     1037
#define IDC_SHOWALL                     1038
#define IDC_REUSEWND                    1038
#define IDC_STOPALL                     1039
#define IDC_DEBUG                       1040
#define IDC_LISTOPER                    1041
#define IDC_RADIO2                      1042
#define IDC_OPER_STARTSTOP              1042
#define IDC_RADIO3                      1043
#define IDC_OPER_STARTDETACH            1043
#define IDC_DEMONBUDDYEXE               1044
#define IDC_RADIO4                      1045
#define IDC_FRAME_OPER                  1045
#define IDC_OPER_EDIT                   1045
#define IDC_RADIO5                      1046
#define IDC_FRAME_TASKS                 1046
#define IDC_OPER_STARTPAUSE             1046
#define IDC_FRAME_TASK                  1047
#define IDC_LBL_TASKNAME                1050
#define IDC_LBL_DIABLOPATH              1051
#define IDC_LBL_ACCPUNT                 1052
#define IDC_LBL_PASSWORD                1053
#define IDC_LBL_SERIAL                  1054
#define IDC_LBL_RESTORECODE             1055
#define IDC_LBL_DEMONBUDDYPATH          1056
#define IDC_AUTHCODE                    1057
#define IDC_LBL_PROFILEPATH             1058
#define IDC_COPYRIGHT                   1060
#define IDC_FRAME_DBLCLK_LIST           1061
#define IDC_FRAME_TASK_CONTROL          1062
#define IDC_FRAME_TIMEOUT               1063
#define IDC_LBL_SCREEN                  1064
#define IDC_LBL_LOGIN                   1065
#define IDC_LBL_JOIN                    1066
#define IDC_LBL_LEFT                    1067
#define IDC_LBL_DISCONNECT              1068
#define IDC_LBL_DIABLO_HUNG             1069
#define IDC_LBL_DEMONBUDDY_HUNG         1070
#define IDC_LBL_FORCE_RESTART           1071
#define IDC_LBL_S1                      1072
#define IDC_LBL_S2                      1073
#define IDC_LBL_S3                      1074
#define IDC_LBL_S4                      1075
#define IDC_LBL_S5                      1076
#define IDC_LBL_S6                      1077
#define IDC_LBL_S7                      1078
#define IDC_TEXT                        1079
#define IDC_NEW_PASSWORD                1080
#define IDC_REPEAT_PASSWORD             1081
#define ID_POPUP_EXIT                   32771
#define ID_POPUP_SHOWWND                32772
#define ID_POPUP_ABOUT                  32773
#define ID_TASK_START                   32774
#define ID_TASK_PAUSERESUME             32775
#define ID_TASK_EDIT                    32776
#define ID_TASK_DELETE                  32777
#define ID_TASK_CLONE                   32778
#define ID_TASK_STOP                    32779
#define ID_TASK_NEW                     32781
#define ID_GLOBAL_SETTINGS              32782
#define ID_MENU_SETTINGS_PASSWORD       32793
#define ID_MENU_SETTINGS                32794
#define ID_TASK_HIDEGAMES               32795
#define ID_TASK_DETACH                  32797
#define ID_TRAY_HIDEALL                 32798
#define ID_TRAY_SHOWALL                 32799
#define ID_TRAY_STOPALL                 32800
#define ID_MENU_LANG_ENG                32802
#define ID_MENU_LANG_CHS                32803
#define ID_MENU_LANG_CHT                32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
